version: '3'
services:

  lair:
    hostname: lair
    container_name: lair_lair
    image: bkeele/lair:latest
    environment:
      LAIR_PASSWORD: "password"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=11014"
      - "traefik.backend=lair"
      - "traefik.frontend.rule=Host:lair.localhost,0.tcp.ngrok.io"

  lairapi:
    hostname: lairapi
    container_name: lair_api
    image: bkeele/lair-api:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.port=11015"
      - "traefik.backend=lairapi"
      - "traefik.frontend.rule=Host:lair.localhost,0.tcp.ngrok.io;PathPrefix:/api"
    volumes:
      - $PWD/plugins:/plugins
      - $HOME/.lair/files:/files

  lairdb:
    hostname: lairdb
    container_name: lair_db
    tty: true
    stdin_open: true
    image: mongo:3.6.1
    restart: always
    entrypoint: /usr/bin/mongod --bind_ip_all --dbpath=/data/db --replSet rs0 --logpath /var/log/mongodb.log --logappend
    volumes:
      - $HOME/.lair/mongodb/data/db:/data/db
      #- $HOME/.lair/mongodb/var/log:/var/log
      #- $HOME/.lair/mongodb/backup:/backup
  traefik:
      hostname: traefik
      container_name: traefik
      image: traefik:1.7
      # command: --logLevel=DEBUG
      ports:
        - "80:80"
        - "443:443"
      restart: always
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - $PWD/traefik.toml:/etc/traefik/traefik.toml
      networks:
        - default
      cap_drop:
        - all
      cap_add:
        - net_bind_service
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.backend=traefik"
        - "traefik.frontend.rule=Host:traefik.localhost"

#   ngrok:
#       hostname: ngrok
#       container_name: lair_ngrok
#       image: wernight/ngrok
#       restart: always
#       labels:
#         - "traefik.enable=true"
#         - "traefik.port=4040"
#         - "traefik.backend=ngrok"
#         - "traefik.frontend.rule=Host:ngrok.localhost"
#       entrypoint: ngrok tcp traefik:443 --authtoken YOUR_AUTH_TOKEN
#       links:
#         - traefik
#       networks:
#         - default
